GA tutorial to find the weights (w1 ~ w6) that maximize Y in the following equation
when x = [4, -2, 3.5, 5, -11, -4.7]
Y = w1x1 + w2x2 + w3x3 + w4x4 + w5x5 + w6x6

In [1]:
import numpy as np

INF = 1001001001

n_weights = 6
inputs = [4, -2, 3.5, 5, -11, -4.7]


sol_per_pop = 8
pop_size = (sol_per_pop, n_weights)
new_pop = np.random.uniform(low=-4.0, high=4.0, size=pop_size)

MAX_GEN = 100
MAX_MATING = 4

### Fitness Function

In [2]:
def calc_fit(inputs, pop):
    return np.sum(pop*inputs, axis=1)

In [3]:
fitness = calc_fit(inputs, new_pop)
fitness

array([ 44.14343344,  25.45223032,   7.15773284, -26.33489278,
        45.86712931, -21.67094931, -39.13876946, -21.80315943])

### Selection

In [4]:
def selection(pop, fitness, n_parents):
    parents = np.empty((n_parents, pop.shape[1]))
    for i in range(n_parents):
        idx = np.where(fitness == np.max(fitness))[0][0]
        parents[i, :] = pop[idx, :]
        fitness[idx] = -INF
    return parents

In [5]:
parents = selection(new_pop, fitness, MAX_MATING)
parents

array([[ 3.78641359,  3.3635113 ,  3.84806283,  0.35547617, -1.98129152,
        -0.08695534],
       [ 3.71401853, -0.70095071, -3.01274194, -0.76202649, -3.228465  ,
        -1.43129193],
       [ 0.49269819,  3.68803113, -1.46336015,  2.74754289, -0.76294153,
        -2.94663599],
       [ 1.10341264, -1.4428801 ,  3.34410317, -2.90936536, -1.26990654,
         2.397486  ]])

### Crossover

In [6]:
def crossover(parents, offspring_size):
    offspring = np.empty(offspring_size)
    crossover_point = np.uint8(offspring_size[1]/2)
    for k in range(offspring_size[0]):
        par1_idx = k % parents.shape[0]
        par2_idx = (k+1) % parents.shape[0]
        offspring[k, 0:crossover_point] = parents[par1_idx, 0:crossover_point]
        offspring[k, crossover_point:] = parents[par2_idx, crossover_point:]
    return offspring

In [7]:
offspring_crossover = crossover(parents, offspring_size=(pop_size[0]-parents.shape[0], n_weights))
offspring_crossover

array([[ 3.78641359,  3.3635113 ,  3.84806283, -0.76202649, -3.228465  ,
        -1.43129193],
       [ 3.71401853, -0.70095071, -3.01274194,  2.74754289, -0.76294153,
        -2.94663599],
       [ 0.49269819,  3.68803113, -1.46336015, -2.90936536, -1.26990654,
         2.397486  ],
       [ 1.10341264, -1.4428801 ,  3.34410317,  0.35547617, -1.98129152,
        -0.08695534]])

### Mutation

In [8]:
def mutation(offspring):
    for i in range(offspring.shape[0]):
        r = np.random.uniform(-1.0, 1.0, 1)
        offspring[i, 4] = offspring[i, 4] + r
    return offspring

In [9]:
offspring_mutation = mutation(offspring_crossover)
offspring_mutation

array([[ 3.78641359,  3.3635113 ,  3.84806283, -0.76202649, -3.43732291,
        -1.43129193],
       [ 3.71401853, -0.70095071, -3.01274194,  2.74754289, -0.66051011,
        -2.94663599],
       [ 0.49269819,  3.68803113, -1.46336015, -2.90936536, -1.02928686,
         2.397486  ],
       [ 1.10341264, -1.4428801 ,  3.34410317,  0.35547617, -2.50962999,
        -0.08695534]])

### New Population

In [10]:
new_pop[0:parents.shape[0], :] = parents
new_pop[parents.shape[0]:, :] = offspring_mutation

In [11]:
new_pop

array([[ 3.78641359,  3.3635113 ,  3.84806283,  0.35547617, -1.98129152,
        -0.08695534],
       [ 3.71401853, -0.70095071, -3.01274194, -0.76202649, -3.228465  ,
        -1.43129193],
       [ 0.49269819,  3.68803113, -1.46336015,  2.74754289, -0.76294153,
        -2.94663599],
       [ 1.10341264, -1.4428801 ,  3.34410317, -2.90936536, -1.26990654,
         2.397486  ],
       [ 3.78641359,  3.3635113 ,  3.84806283, -0.76202649, -3.43732291,
        -1.43129193],
       [ 3.71401853, -0.70095071, -3.01274194,  2.74754289, -0.66051011,
        -2.94663599],
       [ 0.49269819,  3.68803113, -1.46336015, -2.90936536, -1.02928686,
         2.397486  ],
       [ 1.10341264, -1.4428801 ,  3.34410317,  0.35547617, -2.50962999,
        -0.08695534]])

In [13]:
for _ in range(MAX_GEN):
    fitness = calc_fit(inputs, new_pop)
    parents = selection(new_pop, fitness, MAX_MATING)
    offspring_crossover = crossover(parents, offspring_size=(pop_size[0]-parents.shape[0], n_weights))
    offspring_mutation = mutation(offspring_crossover)
    new_pop[0:parents.shape[0], :] = parents
    new_pop[parents.shape[0]:, :] = offspring_mutation
    
    fitness = calc_fit(inputs, new_pop)
    print(fitness[np.where(fitness == np.max(fitness))[0][0]])

494.5459308737538
496.46745966013634
501.0373188546525
501.0373188546525
507.0511710581839
510.36160593036726
517.3731880872435
523.846573354673
523.846573354673
527.4861782690018
527.4861782690018
533.5829759656891
539.5352093640463
539.5352093640463
547.2105491799219
553.2709327786099
563.8580966448692
563.8580966448692
572.6515145484096
579.8528985655975
583.1097129636437
583.1097129636437
583.1097129636437
589.697155106318
589.697155106318
599.9854541018017
599.9854541018017
607.1657096079052
612.1598369632609
613.4199268382928
622.5878222126823
622.5878222126823
629.4222013124912
636.6978113027328
639.4736693727924
648.7091291975622
648.7091291975622
658.2692771938632
665.0798687290238
673.3982098745203
675.6000024831046
675.6000024831046
675.6000024831046
681.6493117866597
684.8042899960618
685.8914008714094
688.0557717779824
694.1051538863308
694.1051538863308
698.1880399844521
698.1880399844521
706.7962982261146
706.7962982261146
708.5797233726748
708.5797233726748
713.16069732